theme: jekyll-theme-slate
title: Welcome to Joaquin Esguerra Jr's homepage!
description: This page is dedicated to my SNHU CS499 Capstone course. Please feel free to bookmark this page to stay updated on my project progress. Thank you for taking the time to visit!
